[package]
name = "updater"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
env_logger = { version = "=0.11.8", features = ["auto-color", "humantime"], default-features = false }
gix-ignore = "=0.16.0"
log = { version = "=0.4.28", features = ["release_max_level_debug"] }
