[package]
name = "updater"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
env_logger = { version = "=0.11.8", features = ["auto-color", "humantime"], default-features = false }
facet = "=0.29.1"
facet-json = "=0.29.1"
gix-ignore = "=0.16.0"
log = { version = "=0.4.28", features = ["release_max_level_debug"] }
regex = { version = "=1.12.2", default-features = false, features = ["std", "perf"] }
taplo = { version = "=0.14.0", default-features = false }
